services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: TIGER
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./BatimenTIGER            # CORRIGÉ ICI
    container_name: spring_backend
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/TIGER
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./tiger-construction-front # CORRIGÉ ICI
    container_name: react_frontend
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: