spring.application.name=BatimenTIGER
server.port=8090

# --- Base de données (MODIFIÉ POUR DOCKER) ---
# Le 'db' ici correspond au nom du service dans votre docker-compose.yml
spring.datasource.url=jdbc:postgresql://db:5432/TIGER
spring.datasource.username=postgres
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# --- OPTIMISATION : Gestion des fichiers ---
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

# --- Actuator (NÉCESSAIRE pour votre healthcheck) ---
# Permet à Docker de savoir que l'application est bien démarrée
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# --- Logs ---
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE