spring.application.name=BatimenTIGER
server.port=8090

# Base de données
spring.datasource.url=jdbc:postgresql://localhost:5433/Constrution
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Fichiers
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

# JWT
jwt.secret=TIGERbatimenSECRET2024JWTauthKeyForAdminPanelBatimenTIGER256bits!
jwt.expiration=86400000
